# 编译并发布到GitHub Pages
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Print current directory
      run: pwd

    - name: List files in .github/workflows
      run: ls -l .github/workflows

    - name: Copy build.yml to dist/.github/workflows
      run: |
        mkdir -p dist/.github/workflows
        cp .github/workflows/static.yml dist/.github/workflows/
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
