name: Build and Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    # 使用用户名和密码连接 SSH
    - name: Deploy dist to Remote Server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        apt-get update
        apt-get install -y sshpass
        sshpass -p $SSH_PASSWORD scp -r ./dist/* $SSH_USERNAME@$SSH_HOST:/etc/nginx/html/
        # 使用 sshpass 工具来传递密码，确保有相应权限和路径正确

    # 可选步骤，如果需要在服务器上执行额外命令
    - name: Additional Commands on Server
      run: |
        sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST 'some-commands-to-run-on-server'
        # 替换 some-commands-to-run-on-server 为实际需要执行的命令
